version: "3.7"
services:
  popular:
    build:
      context: ./golang/
      dockerfile: Dockerfile.dev
    container_name: "popular"
    environment:
      TwitterConsumerKey: ${TWITTER_KEY}
      TwitterConsumerSecret: ${TWITTER_SECRET}
      PixabayKey: ${PIXABAY_KEY}
    volumes:
      - ../:/popular
    ports:
      - "8080:8080"
    tty: true
