version: "3.7"
services:
  popular:
    build:
      context: ./golang/
      dockerfile: Dockerfile.dev
    container_name: "popular"
    environment:
      TWITTER_KEY: ${TWITTER_KEY}
      TWITTER_SECRET: ${TWITTER_SECRET}
      PIXABAY_KEY: ${PIXABAY_KEY}
      PRIVATE_KEY_ID: ${PRIVATE_KEY_ID}
      PRIVATE_KEY: ${PRIVATE_KEY}
    volumes:
      - ../:/popular
    ports:
      - "8080:8080"
    tty: true
